package com.example.chiguaapp;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;

public class DetailActivity extends Activity{
    String url,title,img; SourceConfig source; DrpyEngine engine; LinearLayout root, sourceTabs, playWrap; ProgressBar progress; TextView titleTv, descTv, statTv, sourceTv; ImageView poster; ArrayList<PlayItem> plays=new ArrayList<>(); String activeLine="";
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);} 
    TextView tv(String s,int sp,int color,int style){TextView t=new TextView(this); t.setText(s); t.setTextSize(sp); t.setTextColor(color); t.setTypeface(Typeface.DEFAULT,style); return t;}
    GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp(r)); return g;}
    GradientDrawable strokeBg(int color,int stroke,String sc,float r){GradientDrawable g=bg(color,r); g.setStroke(dp(stroke),Color.parseColor(sc)); return g;}
    GradientDrawable grad(){return new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.parseColor("#26356F"),Color.parseColor("#121827"),Color.parseColor("#090D18")});}

    @Override public void onCreate(Bundle b){super.onCreate(b); url=getIntent().getStringExtra("url"); title=getIntent().getStringExtra("title"); img=getIntent().getStringExtra("img"); if(title==null)title="详情"; source=SourceConfig.load(this); Scraper.useSource(source); engine=new DrpyEngine(this,source); buildUi(); loadDetail();}

    void buildUi(){
        ScrollView sv=new ScrollView(this); sv.setFillViewport(true); sv.setBackgroundColor(Color.parseColor("#080C16")); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(0,0,0,dp(18)); sv.addView(root,new ScrollView.LayoutParams(-1,-2)); setContentView(sv);
        LinearLayout hero=new LinearLayout(this); hero.setOrientation(LinearLayout.VERTICAL); hero.setPadding(dp(16),dp(14),dp(16),dp(18)); hero.setBackground(grad()); root.addView(hero,new LinearLayout.LayoutParams(-1,-2));
        LinearLayout nav=new LinearLayout(this); nav.setGravity(Gravity.CENTER_VERTICAL); nav.setOrientation(LinearLayout.HORIZONTAL);
        TextView back=tv("‹ 返回",16,Color.WHITE,Typeface.BOLD); back.setPadding(0,0,dp(12),0); nav.addView(back,new LinearLayout.LayoutParams(0,dp(40),1)); back.setOnClickListener(v->finish());
        TextView switchSource=tv("切换数据源",13,Color.parseColor("#DDE5FF"),Typeface.BOLD); switchSource.setGravity(Gravity.CENTER); switchSource.setBackground(strokeBg(Color.parseColor("#243053"),1,"#7284FF",18)); nav.addView(switchSource,new LinearLayout.LayoutParams(dp(108),dp(36))); switchSource.setOnClickListener(v->showSourceDialog()); hero.addView(nav);
        LinearLayout head=new LinearLayout(this); head.setOrientation(LinearLayout.HORIZONTAL); head.setPadding(0,dp(12),0,0); hero.addView(head);
        poster=new ImageView(this); poster.setScaleType(ImageView.ScaleType.CENTER_CROP); poster.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.parseColor("#374675"),Color.parseColor("#141A2C")})); head.addView(poster,new LinearLayout.LayoutParams(dp(118),dp(164)));
        LinearLayout info=new LinearLayout(this); info.setOrientation(LinearLayout.VERTICAL); info.setPadding(dp(14),0,0,0); head.addView(info,new LinearLayout.LayoutParams(0,-2,1));
        titleTv=tv(title,22,Color.WHITE,Typeface.BOLD); titleTv.setMaxLines(3); info.addView(titleTv);
        TextView styleTag=tv("ZyFun 详情适配 · 失败自动保留嗅探入口",11,Color.parseColor("#B8FFEA"),Typeface.BOLD); styleTag.setPadding(0,dp(6),0,0); info.addView(styleTag);
        sourceTv=tv("当前数据源 · "+source.title,13,Color.parseColor("#9EADDD"),Typeface.BOLD); sourceTv.setPadding(0,dp(8),0,0); info.addView(sourceTv);
        statTv=tv("正在加载详情...",12,Color.parseColor("#7F8EB8"),Typeface.NORMAL); statTv.setPadding(0,dp(8),0,0); info.addView(statTv);
        TextView playFirst=tv("▶  立即播放",15,Color.WHITE,Typeface.BOLD); playFirst.setGravity(Gravity.CENTER); playFirst.setBackground(bg(Color.parseColor("#5B6CFF"),20)); LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(42)); fp.topMargin=dp(18); info.addView(playFirst,fp); playFirst.setOnClickListener(v->{ if(plays.size()>0)openPlay(plays.get(0)); });
        if(img!=null&&img.startsWith("http")) loadImage(img,poster);
        progress=new ProgressBar(this); progress.setVisibility(View.GONE); root.addView(progress,new LinearLayout.LayoutParams(-1,dp(4)));
        LinearLayout descCard=new LinearLayout(this); descCard.setOrientation(LinearLayout.VERTICAL); descCard.setPadding(dp(16),dp(14),dp(16),dp(14)); LinearLayout.LayoutParams dc=new LinearLayout.LayoutParams(-1,-2); dc.setMargins(dp(14),dp(14),dp(14),0); descCard.setBackground(strokeBg(Color.parseColor("#111827"),1,"#25304A",18)); root.addView(descCard,dc);
        TextView intro=tv("剧情简介",17,Color.WHITE,Typeface.BOLD); descCard.addView(intro); descTv=tv("暂无简介",13,Color.parseColor("#B7C1DC"),Typeface.NORMAL); descTv.setPadding(0,dp(8),0,0); descTv.setLineSpacing(dp(2),1.0f); descCard.addView(descTv);
        TextView lineTitle=tv("播放线路",17,Color.WHITE,Typeface.BOLD); lineTitle.setPadding(dp(16),dp(18),dp(16),dp(8)); root.addView(lineTitle);
        HorizontalScrollView hsv=new HorizontalScrollView(this); hsv.setHorizontalScrollBarEnabled(false); sourceTabs=new LinearLayout(this); sourceTabs.setOrientation(LinearLayout.HORIZONTAL); sourceTabs.setPadding(dp(14),0,dp(14),dp(8)); hsv.addView(sourceTabs); root.addView(hsv);
        TextView epTitle=tv("选集",17,Color.WHITE,Typeface.BOLD); epTitle.setPadding(dp(16),dp(10),dp(16),dp(8)); root.addView(epTitle);
        playWrap=new LinearLayout(this); playWrap.setOrientation(LinearLayout.VERTICAL); playWrap.setPadding(dp(14),0,dp(14),0); root.addView(playWrap);
    }

    void loadDetail(){ progress.setVisibility(View.VISIBLE); if(source.raw!=null&&source.raw.length()>0&&source.raw.contains("var rule")){ engine.runDetail(url,(d,err)->{progress.setVisibility(View.GONE); if(d==null){showFallbackDetail(err);return;} show(d.title,d.content,d.pic,d.plays);}); return; }
        new AsyncTask<Void,Void,Scraper.Detail>(){String err=""; protected Scraper.Detail doInBackground(Void...v){try{return Scraper.detail(url);}catch(Exception e){err=e.toString();return null;}} protected void onPostExecute(Scraper.Detail d){progress.setVisibility(View.GONE); if(d==null){showFallbackDetail(err);return;} show(d.title,d.content,d.pic,d.plays);}}.execute(); }

    void showFallbackDetail(String err){ ArrayList<PlayItem> ps=new ArrayList<>(); ps.add(new PlayItem("网页嗅探", "嗅探播放", url)); show(title, "详情解析暂未完全适配，已保留原页面嗅探播放入口。"+(err!=null&&err.length()>0?"\n\n错误："+err:""), img, ps); }
    void show(String t,String content,String pic,ArrayList<PlayItem> ps){ if(t!=null&&t.length()>0){title=t; titleTv.setText(t);} if(pic!=null&&pic.startsWith("http")) loadImage(pic,poster); descTv.setText(content!=null&&content.length()>0?content:"暂无简介"); plays=ps==null?new ArrayList<>():ps; if(plays.isEmpty()&&url!=null&&url.length()>0)plays.add(new PlayItem("网页嗅探","嗅探播放",url)); statTv.setText("共 "+plays.size()+" 个播放入口 · 支持多线路切换/网页嗅探"); buildLineTabs(); }
    ArrayList<String> lines(){ArrayList<String> out=new ArrayList<>(); for(PlayItem p:plays){ if(!out.contains(p.source))out.add(p.source);} if(out.size()==0)out.add("默认线路"); return out;}
    void buildLineTabs(){ sourceTabs.removeAllViews(); ArrayList<String> ls=lines(); if(activeLine.length()==0||!ls.contains(activeLine))activeLine=ls.get(0); for(String l:ls){ TextView b=tv(l,13,Color.WHITE,Typeface.BOLD); b.setGravity(Gravity.CENTER); b.setPadding(dp(14),0,dp(14),0); b.setBackground(l.equals(activeLine)?bg(Color.parseColor("#5B6CFF"),18):strokeBg(Color.parseColor("#151B2E"),1,"#33405E",18)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(38)); lp.rightMargin=dp(8); sourceTabs.addView(b,lp); b.setOnClickListener(v->{activeLine=l; buildLineTabs();}); } buildEpisodes(); }
    void buildEpisodes(){ playWrap.removeAllViews(); LinearLayout row=null; int col=0; for(PlayItem p:plays){ if(!p.source.equals(activeLine))continue; if(row==null||col==3){ row=new LinearLayout(this); row.setOrientation(LinearLayout.HORIZONTAL); playWrap.addView(row,new LinearLayout.LayoutParams(-1,dp(46))); col=0;} TextView ep=tv(p.name,13,Color.parseColor("#E8EDFF"),Typeface.BOLD); ep.setSingleLine(true); ep.setGravity(Gravity.CENTER); ep.setBackground(strokeBg(Color.parseColor("#141B2F"),1,"#2B3754",14)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(40),1); lp.rightMargin=dp(8); lp.bottomMargin=dp(8); row.addView(ep,lp); ep.setOnClickListener(v->openPlay(p)); col++; } if(playWrap.getChildCount()==0){TextView empty=tv("暂无播放入口，可尝试切换数据源",14,Color.parseColor("#8EA0C4"),Typeface.NORMAL); empty.setPadding(0,dp(14),0,dp(14)); playWrap.addView(empty);} }
    void openPlay(PlayItem p){ Intent in=new Intent(this,PlayerActivity.class); in.putExtra("input",p.input); in.putExtra("title",title+" · "+p.name); in.putExtra("series_title",title); in.putExtra("line",p.source); ArrayList<String> names=new ArrayList<>(); ArrayList<String> inputs=new ArrayList<>(); int currentIndex=0; for(PlayItem it:plays){ if(it==null)continue; String src=it.source==null?"默认线路":it.source; if(!src.equals(activeLine))continue; names.add(it.name==null?"播放":it.name); inputs.add(it.input==null?"":it.input); if(it==p)currentIndex=names.size()-1; } in.putStringArrayListExtra("episode_names",names); in.putStringArrayListExtra("episode_inputs",inputs); in.putExtra("episode_index",currentIndex); startActivity(in); }
    void showSourceDialog(){ ArrayList<SourceConfig> all=SourceConfig.loadAll(this); String[] names=new String[all.size()]; for(int i=0;i<all.size();i++)names[i]=all.get(i).title; new AlertDialog.Builder(this).setTitle("切换数据源").setItems(names,(d,which)->{SourceConfig.setActive(this,which); Toast.makeText(this,"已切换到："+names[which],Toast.LENGTH_SHORT).show(); Intent in=new Intent(this,MainActivity.class); in.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_NEW_TASK); startActivity(in); finish();}).setNegativeButton("取消",null).show(); }
    void loadImage(String u,ImageView iv){iv.setTag(u); new AsyncTask<Void,Void,Bitmap>(){protected Bitmap doInBackground(Void...v){try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection(); c.setConnectTimeout(8000); c.setReadTimeout(8000); c.setRequestProperty("User-Agent","Mozilla/5.0"); return BitmapFactory.decodeStream(c.getInputStream());}catch(Exception e){return null;}} protected void onPostExecute(Bitmap b){if(b!=null&&u.equals(iv.getTag()))iv.setImageBitmap(b);}}.execute();}
}
