package com.example.chiguaapp;

import android.app.*;import android.os.*;import android.webkit.*;import java.io.*;import java.net.*;import java.util.*;import org.json.*;

public class DrpyEngine{
    Activity act; WebView web; SourceConfig source; String lastResult=""; String currentHost="";
    public interface Callback<T>{void done(T data,String err);}
    public DrpyEngine(Activity a, SourceConfig s){act=a; source=s; currentHost=s.host; web=new WebView(a); WebSettings ws=web.getSettings(); ws.setJavaScriptEnabled(true); ws.setDomStorageEnabled(true); web.addJavascriptInterface(new Bridge(),"Android"); web.loadData("<html><body>drpy</body></html>","text/html","utf-8");}
    public class Bridge{
        @JavascriptInterface public String request(String url,String opt){try{return http(abs(url));}catch(Exception e){return "";}}
        @JavascriptInterface public void setResult(String json){lastResult=json==null?"":json;}
        @JavascriptInterface public String log(String s){return s;}
    }
    String baseJs(String input){String raw=source.raw==null?"":source.raw; return "var input="+q(input)+";var MY_PAGE=1;var MY_PAGECOUNT=999;var MY_TOTAL=99999;"+
            "var MOBILE_UA='Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36';var HOST='"+js(source.host)+"';"+
            "var document={html:''};var localStore={};function getItem(k){return localStore[k]||'';}function setItem(k,v){localStore[k]=String(v||'');}"+
            "var $js={toString:function(fn){var s=String(fn);var a=s.indexOf('{'),b=s.lastIndexOf('}');return 'js:'+(a>=0&&b>a?s.substring(a+1,b):s);}};"+
            "function request(u,o){var r=Android.request(String(u||''),JSON.stringify(o||{}));document.html=r;return r;}function fetch(u,o){return request(u,o);}"+
            "function setResult(v){Android.setResult(JSON.stringify(v||[]));}function log(v){Android.log(String(v));}"+
            jsRuntime()+raw+"\n;";}
    String wrapRun(String input,String key){return "(function(){try{"+baseJs(input)+"var code=rule["+q(key)+"]||'';var real=realInput("+q(key)+"); if(typeof code==='object'){var html=request(real);Android.setResult(JSON.stringify(parseDetailObj(html,code)));return 'ok';} code=String(code); if(code.indexOf('js:')===0){code=code.substring(3);eval(code); if(typeof VODS!=='undefined')Android.setResult(JSON.stringify(VODS)); else if(typeof VOD!=='undefined'&&VOD)Android.setResult(JSON.stringify(VOD)); return 'ok';} var html=request(real);Android.setResult(JSON.stringify(parseListSel(html,code)));return 'ok';}catch(e){Android.setResult(JSON.stringify({error:String(e),stack:e.stack||''}));return 'err:'+e;}})()";}
    public void runList(String key,String input,Callback<ArrayList<VideoItem>> cb){lastResult=""; web.evaluateJavascript(wrapRun(input,key), v->{try{cb.done(parseItems(lastResult),"");}catch(Exception e){cb.done(new ArrayList<>(),e.toString()+" raw="+lastResult);}});}
    public void runDetail(String input,Callback<DetailData> cb){lastResult=""; web.evaluateJavascript(wrapRun(input,"二级"), v->{try{cb.done(parseDetail(lastResult),"");}catch(Exception e){cb.done(null,e.toString()+" raw="+lastResult);}});}
    public void runLazy(String input,Callback<String> cb){lastResult=""; String js="(function(){try{"+baseJs(input)+"document.html=request(input);var code=rule['lazy']||''; code=String(code); if(code.indexOf('js:')===0)code=code.substring(3); eval(code); if(typeof input==='object'){Android.setResult(JSON.stringify(input));}else{Android.setResult(JSON.stringify({url:String(input||'')}));} return 'ok';}catch(e){Android.setResult(JSON.stringify({url:"+q(input)+",error:String(e)}));return 'err';}})()"; web.evaluateJavascript(js,v->{try{JSONObject o=new JSONObject(lastResult); cb.done(o.optString("url",input),"");}catch(Exception e){cb.done(input,e.toString());}});}
    static String jsRuntime(){return "function absu(u){u=String(u||'');if(/^https?:/.test(u))return u;if(u.indexOf('//')===0)return 'https:'+u;if(u.charAt(0)==='/')return rule.host+u;return rule.host+'/'+u;}"+
            "function realInput(k){var p=input,m;if(k==='搜索'){var su=rule.searchUrl||'';m=p.match(/\\/search\\/([^\\/]+)\\/(\\d+)/);var kw=m?decodeURIComponent(m[1]):'';var pg=m?m[2]:'1';return absu(su.replace('**',encodeURIComponent(kw)).replace('fypage',pg));}if(k==='一级'){m=p.match(/\\/category\\/([^\\/]+)\\/(\\d+)/);var cl=m?m[1]:'';var pg=m?m[2]:'1';return absu((rule.url||'/').replace('fyclass',cl).replace('fypage',pg).replace('fyfilter',''));}return absu(p&&p!=='/'?p:(rule.homeUrl||rule.host));}"+
            "function qsa(ctx,sel){try{sel=String(sel||'').replace(/:eq\\(([-\\d#]+)\\)/g,function(_,n){return n==='#id'?'':':nth-child('+(parseInt(n)+1)+')'});return Array.prototype.slice.call((ctx||documentObj).querySelectorAll(sel));}catch(e){return[];}}"+
            "function one(ctx,sel){var m=String(sel||'').match(/:eq\\((-?\\d+)\\)/);var clean=String(sel||'').replace(/:eq\\(-?\\d+\\)/g,'');var a=qsa(ctx,clean);if(m){var i=parseInt(m[1]);if(i<0)i=a.length+i;return a[i]||null;}return a[0]||null;}"+
            "function val(el,expr){if(!el)return'';var ps=String(expr||'').split('&&');var node=el;if(ps[0]&&ps[0]!=='body'&&ps[0]!=='a'&&ps[0]!=='img'&&ps[0]!=='script')node=one(el,ps[0])||el;else if(ps[0]&&ps[0]!=='body')node=one(el,ps[0])||el;var a=ps[ps.length-1];if(a==='Text')return (node.textContent||'').trim();if(a==='Html')return node.innerHTML||'';return node.getAttribute(a)||'';}"+
            "function parseDoc(html){return new DOMParser().parseFromString(String(html||''),'text/html');}"+
            "function parseListSel(html,ruleStr){documentObj=parseDoc(html);var p=String(ruleStr||'').split(';');var nodes=qsa(documentObj,p[0]||'body');return nodes.map(function(n){return{title:val(n,p[1]),img:absu(val(n,p[2])),desc:val(n,p[3]),url:absu(val(n,p[4]))};}).filter(function(x){return x.title&&x.url;});}"+
            "function parseDetailObj(html,o){documentObj=parseDoc(html);var title=val(documentObj,o.title||'')||'';var img=absu(val(documentObj,o.img||''));var desc=val(documentObj,o.desc||'');var content=val(documentObj,o.content||'');var tabs=qsa(documentObj,o.tabs||'body');var from=[],groups=[];for(var i=0;i<tabs.length;i++){from.push(val(tabs[i],o.tab_text||'body&&Text')||('线路'+(i+1)));var listSel=String(o.lists||'').replace('#id',i);var its=qsa(documentObj,listSel),arr=[];for(var j=0;j<its.length;j++){var nm=val(its[j],o.list_text||'body&&Text')||('第'+(j+1)+'集');var u=absu(val(its[j],o.list_url||'a&&href')||val(its[j],'a&&href'));arr.push(nm+'$'+u);}groups.push(arr.join('#'));}return{vod_name:title,vod_pic:img,vod_remarks:desc,vod_content:content,vod_play_from:from.join('$$$'),vod_play_url:groups.join('$$$')};}";}
    ArrayList<VideoItem> parseItems(String json)throws Exception{ArrayList<VideoItem> out=new ArrayList<>(); if(json==null||json.length()<1)return out; if(json.trim().startsWith("{")){JSONObject o=new JSONObject(json); if(o.has("error"))throw new RuntimeException(o.optString("error")+" "+o.optString("stack"));}
        JSONArray arr=new JSONArray(json); for(int i=0;i<arr.length();i++){JSONObject o=arr.getJSONObject(i); String t=first(o,"title","vod_name","name"); String u=first(o,"url","vod_id"); String pic=first(o,"img","vod_pic","pic_url"); String d=first(o,"desc","vod_remarks","remarks"); out.add(new VideoItem(t,u,pic,d));} return out;}
    DetailData parseDetail(String json)throws Exception{JSONObject o=new JSONObject(json); if(o.has("error"))throw new RuntimeException(o.optString("error")+" "+o.optString("stack")); DetailData d=new DetailData(); d.title=first(o,"vod_name","title"); d.content=first(o,"vod_content","content","desc"); d.pic=first(o,"vod_pic","img"); String from=o.optString("vod_play_from","道长在线"); String urls=o.optString("vod_play_url",""); String[] froms=from.length()>0?from.split("\\$\\$\\$"):new String[]{"道长在线"}; String[] groups=urls.length()>0?urls.split("\\$\\$\\$"):new String[0]; for(int gi=0;gi<Math.max(froms.length,groups.length);gi++){ String src=gi<froms.length&&froms[gi].trim().length()>0?froms[gi].trim():("线路"+(gi+1)); String block=gi<groups.length?groups[gi]:""; if(block.length()==0)continue; String[] ps=block.split("#"); for(String p:ps){ if(p==null||p.trim().length()==0)continue; int x=p.indexOf('$'); String name=x>0?p.substring(0,x):p; String input=x>0?p.substring(x+1):p; d.plays.add(new PlayItem(src,name,input)); }} if(d.plays.isEmpty())d.plays.add(new PlayItem("默认线路","打开原页",source.host)); return d;}
    static String first(JSONObject o,String...ks){for(String k:ks){String v=o.optString(k,""); if(v.length()>0)return v;}return "";}
    static String q(String s){return JSONObject.quote(s==null?"":s);} static String js(String s){return (s==null?"":s).replace("\\","\\\\").replace("'","\\'").replace("\n","\\n");}
    String abs(String u){if(u.startsWith("http://")||u.startsWith("https://"))return u; if(u.startsWith("//"))return "https:"+u; if(u.startsWith("/"))return currentHost+u; return currentHost+"/"+u;}
    String http(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection(); c.setConnectTimeout(15000); c.setReadTimeout(15000); c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36"); c.setRequestProperty("Referer",currentHost+"/"); InputStream is=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream(); ByteArrayOutputStream out=new ByteArrayOutputStream(); byte[] b=new byte[8192]; int n; while((n=is.read(b))>0)out.write(b,0,n); return out.toString("UTF-8");}
    public static class DetailData{public String title="详情",content="",pic=""; public ArrayList<PlayItem> plays=new ArrayList<>();}
}
